{% set name = "nsync" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b7e75b17957c62bd02dd73890bde22da3a564903fcaad651b395453d41d3325b

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.0
    - make  # [not win]

test:
  commands:
    - if not exist %LIBRARY_LIB%\\nsync.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\nsync_cpp.lib exit 1  # [win]
    - test -f ${PREFIX}/lib/libnsync.a  # [not win]
    - test -f ${PREFIX}/lib/libnsync_cpp.a  # [not win]

about:
  home: https://github.com/google/nsync
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'nsync is a C library that exports various synchronization primitives, such as mutexes'
  description: |
      nsync is a C library that exports various synchronization primitives:
      locks
      condition variables
      run-once initialization
      waitable counter (useful for barriers)
      waitable bit (useful for cancellation, or other conditions)
  doc_url: https://github.com/google/nsync
  dev_url: https://github.com/google/nsync

extra:
  recipe-maintainers:
    - njzjz
