{% set name = "nsync" %}
{% set version = "1.29.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1d63e967973733d2c97e841e3c05fac4d3fa299f01d14c86f2695594c7a4a2ec

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.0
    - make  # [not win]

test:
  commands:
    - if not exist %LIBRARY_LIB%\\nsync.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\nsync_cpp.lib exit 1  # [win]
    - test -f ${PREFIX}/lib/libnsync.a  # [not win]
    - test -f ${PREFIX}/lib/libnsync_cpp.a  # [not win]

about:
  home: https://github.com/google/nsync
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: nsync is a C library that exports various synchronization primitives, such as mutexes
  description: |
    nsync is a C library that exports various synchronization primitives:
    locks
    condition variables
    run-once initialization
    waitable counter (useful for barriers)
    waitable bit (useful for cancellation, or other conditions)
  doc_url: https://github.com/google/nsync
  dev_url: https://github.com/google/nsync

extra:
  recipe-maintainers:
    - njzjz
